# Generated by Django 4.1.7 on 2023-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_archive',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=8),
        ),
    ]
